@startuml

node "Architecture Application" {
    component "Activity" as activity
    component "View Model" as viewModel
    component "Repository"" as repository
    component "Data Source" as dataSource
}

database "SQL Lite" as databaseSQL
database "Data Store" as datastore
cloud "Api Service" as apiService

activity <--> viewModel
viewModel <--> repository
repository <--> dataSource
dataSource <--> databaseSQL
dataSource <--> datastore
dataSource <--> apiService

@enduml